# Generated by Django 6.0.5 on 2026-05-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название тренировки')),
                ('workout_date', models.DateField(verbose_name='Дата тренировки')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность (мин)')),
                ('fatigue_level', models.IntegerField(verbose_name='Уровень усталости')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
            },
        ),
    ]
