# Generated by Django 6.0.5 on 2026-05-16 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField(verbose_name='Количество подходов')),
                ('reps', models.PositiveIntegerField(verbose_name='Повторения')),
                ('weight', models.FloatField(verbose_name='Вес (кг)')),
                ('rpe', models.IntegerField(verbose_name='RPE')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exercise', verbose_name='Упражнение')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workout', verbose_name='Тренировка')),
            ],
            options={
                'verbose_name': 'Подход упражнения',
                'verbose_name_plural': 'Подходы упражнений',
            },
        ),
    ]
