# Generated by Django 6.0.5 on 2026-05-16 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_workoutset'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_hours', models.FloatField(verbose_name='Часы сна')),
                ('stress_level', models.IntegerField(verbose_name='Уровень стресса')),
                ('energy_level', models.IntegerField(verbose_name='Уровень энергии')),
                ('mood', models.CharField(max_length=100, verbose_name='Самочувствие')),
                ('recovery_score', models.FloatField(verbose_name='Recovery Score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workout', verbose_name='Тренировка')),
            ],
            options={
                'verbose_name': 'Показатель восстановления',
                'verbose_name_plural': 'Показатели восстановления',
            },
        ),
    ]
