# Generated by Django 6.0.5 on 2026-05-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_recoverymetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='Вес (кг)')),
                ('body_fat', models.FloatField(verbose_name='Процент жира')),
                ('muscle_mass', models.FloatField(verbose_name='Мышечная масса')),
                ('measurement_date', models.DateField(verbose_name='Дата измерения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Измерение тела',
                'verbose_name_plural': 'Измерения тела',
            },
        ),
    ]
